# Generated by Django 4.2.1 on 2023-07-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_blogs_alter_contact_contacted_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('full_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('degree', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('freelance', models.CharField(max_length=50)),
            ],
        ),
    ]
