# Generated by Django 4.2.1 on 2023-07-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_desc', models.TextField()),
                ('fields', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('level', models.IntegerField()),
            ],
        ),
    ]
