# Generated by Django 4.2.1 on 2023-07-27 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='skills_desc',
        ),
    ]
