# Generated by Django 4.2.1 on 2023-07-27 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_skills_skills_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
